title: Team Hollow
description: >-
    Description

twitter: hollowdev
github:  teamhollow

# Build settings
theme: minima
plugins:
    - jekyll-feed

# Collections
collections:
    articles:
        output: true
        permalink: /article/:path
    pages:
        output: true
        permalink: /:path
    redirects:
        output: true
        permalink: /:path

# Minima Config
minima:
    skin: dark
    social_links:
        twitter: hollowdev
        github:  teamhollow
